### ISSUE TITLE
Memory usage increases linearly over time

### ISSUE THREAD

**Issue by joshsouza** [cloudflare/mmproxy#10]
First: Thanks so much for this tool, our initial testing is showing it solving our problem quite well.

Context: We have put mmproxy in a container within a kubernetes pod as a sidecar and it works as expected (handling PROXY protocol traffic and resulting in properly spoofed traffic in the application pod). Our k8s pod is then behind an AWS ELB running the proxy protocol.

What we've seen: mmproxy's memory usage appears to be growing at a linear rate over time growing from minimal to ~3Gb over 5 days. I'm not sure if this is an indication of a problem with mmproxy or something I have configured incorrectly. I also don't know where to start in getting you useful information to help diagnose, but I'm happy to dig in.

**Comment by majek** [comment]
Hurray, thanks for feedback. I guess we need to look for memory leaks.

**Comment by joshsouza** [comment]
Confirmed! Thanks!
