### ISSUE TITLE
Tagging a release

### ISSUE THREAD

**Issue by darix** [cloudflare/mmproxy#5]
I would be happy to package mmproxy for linux but it would be easier from release tags.
And is it possible to support building against system copies of libmill and libseccomp and only fall back to the intree copy?

**Comment by majek** [comment]
2018.07.01 tag added

**Comment by darix** [comment]
Thank you!

**Comment by darix** [comment]
the tarball from github doesn't include the libmill and libseccomp sources and is unusable

**Comment by darix** [comment]
Using a quickly hacked up meson file now to build against the system copy of the libraries

https://build.opensuse.org/package/view_file/home:darix:playground/mmproxy/meson.build?expand=1
