### ISSUE TITLE
Integration with a system

### ISSUE THREAD

**Issue by darix** [cloudflare/mmproxy#8]
I want to discuss an upstream solution how to launch mmproxy on the server. my initial thought would be instantiated system services and setting the commandline in /etc/systemd/system/mmproxy@instance1/override.conf

Any other solutions you would prefer? What does cloudflare propose for this?

**Comment by majek** [comment]
I'm not sure I follow. So far all options are passed with command line. If you are proposing systemd config, then sure, file a PR.

**Comment by majek** [comment]
For my taste command line parameters work fine thus far. Perhaps a config file would be useful if there were more parameters.

**Comment by darix** [comment]
how do you launch it in your infrastructure? how would you make it easy for the user to pass those cmdline arguments in without editing the file?:)

my first suggestion would be

```
# /etc/sysconfig/mmproxy
MMPROXY_CMDLINE="...."
```

and a service file that loads this file and then does

```
ExecStart=/usr/sbin/mmproxy $MMPROXY_CMDLINE"
```

If that is a solution you like I think it would be good to ship that as a default and I will be happily provide a PR for this.
